root: true
env:
  browser: true
  es2021: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
  project: './tsconfig.json'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
plugins:
  - '@typescript-eslint'
  - react
  - react-hooks
settings:
  react:
    version: detect
rules:
  # TypeScript rules
  '@typescript-eslint/consistent-type-imports':
    - error
    - prefer: type-imports
  '@typescript-eslint/no-explicit-any': error
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'

  # React rules
  react/react-in-jsx-scope: off
  react/prop-types: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn

  # General rules
  func-style: off
  prefer-arrow-callback: error
  consistent-return: off
  no-console:
    - warn
    - allow:
        - warn
        - error
        - log

ignorePatterns:
  - dist/
  - node_modules/
  - '*.js'
  - '*.cjs'
  - '*.mjs'
  - '**/__tests__/**'
  - '**/setupTests.ts'
  - '**/*.test.ts'
  - '**/*.test.tsx'
