const { withAndroidManifest, withDangerousMod } = require('expo/config-plugins');
const path = require('node:path');
const fs = require('node:fs');

// Android blocks cleartext HTTP by default, and the local wake harness under
// scripts/ is plain HTTP on the developer's machine. Without an exception the
// app's token refresh and device registration fail with UnknownServiceException
// and the wake path looks broken for a reason that has nothing to do with it.
//
// Scoped to loopback rather than `usesCleartextTraffic="true"`: that attribute is
// app-wide and would follow anyone who copies this example into a real app, where
// the backend is HTTPS and cleartext is never wanted. Here it reaches only the
// host as seen from the device — 10.0.2.2 on the emulator, 127.0.0.1/localhost
// over `adb reverse` on hardware.
//
// A LAN IP is deliberately not included: add one here if you point the registry
// URL at your machine's address instead of forwarding the port.
const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withLocalRigCleartext.js — do not edit. -->
<network-security-config>
  <domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="false">localhost</domain>
    <domain includeSubdomains="false">127.0.0.1</domain>
    <domain includeSubdomains="false">10.0.2.2</domain>
  </domain-config>
</network-security-config>
`;

const withConfigFile = (config) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, 'app/src/main/res/xml');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'network_security_config.xml'), NETWORK_SECURITY_CONFIG);
      return cfg;
    },
  ]);

const withManifestReference = (config) =>
  withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0];
    if (!app) throw new Error('withLocalRigCleartext: no <application> in the manifest');
    app.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    return cfg;
  });

module.exports = (config) => withManifestReference(withConfigFile(config));
