/**
 * Service Subscription Agreement — body content rendered in the acceptance gate.
 *
 * IMPORTANT: this is a temporary, hand-maintained copy of the agreement body
 * published at www.dialstack.ai/ssa (the page's legal sections, scrubbed of
 * page chrome and scripts). It exists so the gate can show the full agreement
 * inline — sourced from the same text the customer reviews — without depending
 * on a cross-origin embed of the hosted page.
 *
 * Both copies (this one and the hosted page) must be derived from one source of
 * truth, and the acceptance API should serve the body + version so this constant
 * can be retired. That convergence is tracked separately; until then, keep this
 * in sync with the hosted page and bump SSA_LAST_UPDATED on any change.
 *
 * The markup is static and authored here (no interpolation, no user input), so
 * rendering it via dangerouslySetInnerHTML carries no injection risk.
 */

// TODO: retire this hand-maintained copy once the agreement body is served from
// the acceptance API (single source of truth) instead of bundled here.
export const SSA_LAST_UPDATED = 'June 16, 2026';

export const SSA_AGREEMENT_HTML = `
<p class="ssa-intro">Thanks for using our phone service. We built it to be a reliable business phone system, and we want the terms you agree to to be just as straightforward. This agreement is the contract between you and us. We've written it in plain language, but it is a real, binding legal contract, so please read it, especially the parts about emergency (911) calling, what you can't do on the network, and the limits on our liability.</p>

<p><span class="lead-in">Who "we" and "you" are.</span> When we say "we," "us," or "our" (also called the "Provider" in places where a legal label is needed), we mean <strong>DialStack, Inc.</strong>, a Delaware corporation. We are the licensed carrier behind your phone service. You may have signed up through another company's product, your "Platform Partner," which may present this service under its own brand. That's expected: the Platform Partner runs your account experience and billing, and we are the carrier underneath. When we say "you" or "your," we mean the business that owns this account and everyone who uses the service under it.</p>

<p><span class="lead-in">How you accept.</span> By clicking "I Agree," or by using the service, you agree to this contract on behalf of your business. When you accept, you represent, warrant, and agree to three things: (1) you're at least 18 and have the authority to bind your business; (2) <strong>you have been informed by us of, and have read and understood, the 911 emergency-calling limitations in Section 7, including the reasons to keep at least one backup way to reach 911 at each location, and you agree to the release and waiver in that section</strong>; and (3) you agree to everything below. If you don't agree, don't use the service.</p>

<p>This service is for business use only.</p>

<h2>1. The Service</h2>
<p><span class="lead-in">What we provide.</span> We provide a hosted internet phone (VoIP) service: voice calling, phone numbers (DIDs), voicemail, call management features, and related functionality. The specific services on your account are described in Schedule 1 and in your account portal. We operate and maintain the platform and deliver the service over the internet; you provide and maintain the equipment and internet connection needed to use it (see Section 2).</p>
<p><span class="lead-in">Business use, in the U.S., no international calling.</span> The service is for your internal business use within the United States. International calling is not included today, and outbound international calls are blocked; if we offer international calling in the future, it will be billed per minute. You're responsible for any charges for calls between the continental U.S. and Alaska or Hawaii at the rates in your portal. We can block traffic to or from any international destination, or to number ranges like 900 and 976, when we need to in order to follow the law, protect our network, or stop fraud or abuse.</p>
<p><span class="lead-in">Your Platform Partner's services are separate.</span> Anything you get from your Platform Partner beyond the phone service itself is governed by your agreement with them, not this one. We're not responsible for the Platform Partner's own products or services.</p>
<p><span class="lead-in">We may improve or change the service.</span> We may modify the features and functionality of the service over time. If a change will meaningfully degrade the service you rely on, we'll use commercially reasonable efforts to give you advance notice. (Changes to <em>this contract</em> are handled differently, in Section 16.)</p>

<h2>2. Your Account</h2>
<p><span class="lead-in">Account setup and accurate information.</span> Before the service is used, an account must be set up (by you, or by your Platform Partner on your behalf). You agree to keep your account information accurate and current, including the physical location of each user (this matters for 911, see Section 7). You sign in with a username and password or through a supported single sign-on (SSO) provider. You're also responsible for securing your own networks and devices against unauthorized access and for backing up your own data, using good computing practices.</p>
<p><span class="lead-in">Keep your credentials safe.</span> You're responsible for keeping your account credentials confidential and for everything that happens under your account, including anything your users do and any unauthorized use. Don't share your credentials. Tell us right away if you think someone has gained unauthorized access, by emailing <a href="mailto:support@dialstack.ai">support@dialstack.ai</a> (or the support contact your Platform Partner provides).</p>
<p><span class="lead-in">Your Platform Partner has admin access.</span> Your Platform Partner has its own independent administrative access to your account through our platform, using its own credentials. Actions the Platform Partner takes on your behalf, like provisioning, configuring, or changing your service, are treated as authorized by you.</p>
<p><span class="lead-in">Fraud protection.</span> If we suspect fraudulent or abusive activity on your account, we can interrupt, restrict, or terminate the service without notice. You agree to cooperate with any fraud investigation and to take reasonable fraud-prevention steps we ask for. You are fully responsible for all charges and will not be excused from paying for service on the basis that some or all of the calls were fraudulent.</p>

<h2>3. Using the Service Responsibly</h2>
<p>You agree to use the service only as allowed here and under all applicable laws. Because we are the carrier of record, what happens on your account is traffic on our regulated network, so these rules carry real legal and regulatory weight. You agree that you and your users will not:</p>
<ul>
  <li><strong>Break the law or harm others.</strong> No use that is unlawful, fraudulent, criminal, libelous, threatening, harassing, obscene, or that infringes someone else's intellectual property. No using the service to exploit or harm children.</li>
  <li><strong>Run prohibited calling campaigns.</strong> No autodialing or predictive dialing, continuous or iterative dialing, fax blasting or junk faxing, robocalls, telemarketing, bulk or unsolicited messages, recorded-message broadcasts, or call-center/bulk call-in operations. In short: no use outside reasonable internal business calling. (If you have a high-volume use case, contact us to discuss whether it can be accommodated; we are not obligated to permit it.)</li>
  <li><strong>Spoof or manipulate traffic.</strong> No altering, faking, or stripping caller ID, calling-party numbers, signaling, or other call detail, and no re-originating or re-classifying traffic to disguise where it came from or what type it is. (This protects everyone's compliance with caller-ID authentication rules.)</li>
  <li><strong>Record calls unlawfully.</strong> Don't record any communication except in strict compliance with applicable law.</li>
  <li><strong>Abuse or disrupt the service.</strong> No interfering with the network, other customers, or our support operations; no introducing malware or corrupted files; no reselling the service or running a service bureau.</li>
  <li><strong>Misuse access or branding.</strong> Don't access the service except through the interface we or your Platform Partner provide (no scripts or crawlers), and don't use anyone's trademarks or remove proprietary notices without permission.</li>
  <li><strong>Use it for life-safety or high-risk systems.</strong> The service isn't built for uses where a failure could cause death, injury, or serious physical or environmental harm (for example, medical life-support, or monitoring or control of hazardous or critical facilities).</li>
</ul>
<p><span class="lead-in">Fair use.</span> Domestic calling included with the service is subject to the Fair Use Policy in Schedule 1.</p>
<p><span class="lead-in">What happens if you break these rules.</span> We can take any lawful action we think is appropriate, including a warning, suspending or limiting the service, or terminating your account, in our discretion, immediately and without notice. We may take any of these actions without notice and without liability to you or any third party, and we have no obligation to take any of them. We may also cut off voice calls longer than 2 hours and fax calls longer than 1 hour. If we suspend (rather than terminate) your account and you cure the violation, we may turn the service back on and may charge a $100 restoration fee. Either way, you remain responsible for fees for service used up to the date of termination, and this doesn't limit our other remedies.</p>

<h2>4. Your Content and Your Users</h2>
<p><span class="lead-in">You own and are responsible for your content.</span> "Your Content" means everything you and your users send, upload, record, or transmit through the service. You keep all the intellectual property rights you have in it, and you're solely responsible for it, including any harm or third-party claims it causes.</p>
<p><span class="lead-in">The license you give us.</span> So that we can carry and deliver your communications, you give us a non-exclusive, worldwide, royalty-free, sublicensable, transferable, perpetual, irrevocable license to use, store, transmit, reproduce, and deliver Your Content as needed to provide the service. You confirm you have the rights to grant this license. The license is for running the service and for our lawful retention, backup, and de-identified analytics (see Section 9); it survives termination only to that extent, and we don't claim ownership of Your Content.</p>
<p><span class="lead-in">We don't have to store or screen it.</span> We try to store things like voicemail, call logs, recordings, and messages, but we're not obligated to and aren't responsible if they're lost or deleted. We may (but don't have to) screen, filter, or remove content, at our discretion and without liability.</p>
<p><span class="lead-in">Your users.</span> We don't control and aren't responsible for what your employees, agents, or other users do on the service, or for the content they create. Content created by your users may be protected by others' intellectual property rights; don't copy or reuse it without permission.</p>

<h2>5. Billing and Payment</h2>
<p><span class="lead-in">Who bills you.</span> Your Platform Partner bills you as our billing agent, charging the card or payment method on file. Your specific rates are shown in your account portal. Fees include recurring charges, usage charges, applicable taxes, and regulatory fees (described below and in Schedule 1).</p>
<p><span class="lead-in">How billing works (advance for recurring, arrears for usage).</span> Recurring fees are billed <strong>monthly in advance</strong> for the month ahead, starting when your service begins (prorated for a partial first month) and then on the first of each month, based on the resources provisioned (users, phone numbers, and the like) as of the billing date. Usage-based charges, overage charges, and one-time charges are billed <strong>monthly in arrears</strong> for the prior month. Payment is due on receipt of invoice unless you and your Platform Partner agree otherwise.</p>
<p><span class="lead-in">Adding and removing resources mid-month.</span> If you add resources mid-month, we prorate the recurring fee for the rest of that month and it appears on your next invoice. If you remove resources mid-month, the change takes effect at the start of the next billing period, and recurring fees already billed in advance for the current month are <strong>not refunded</strong> (taxes and fees on them have already been assessed and remitted).</p>
<p><span class="lead-in">Taxes.</span> You're responsible for all applicable taxes, fees, and surcharges imposed on the service or your use of it, except taxes on our income. Many of these are telecom-specific (for example, certain excise, utility, and gross-receipts taxes and government surcharges), vary by jurisdiction, and generally apply even if you're exempt from sales tax. If you give your Platform Partner a valid, current tax-exemption certificate, we'll apply it, to the extent the law allows, to the taxes it actually covers (usually sales and use tax); it doesn't relieve you of other taxes, fees, or surcharges.</p>
<p><span class="lead-in">Regulatory fees, taxes, and our recovery fees.</span> Your bill includes two distinct categories, and we keep them separate. First, genuine government taxes, fees, and surcharges that we pass through, including Federal and state Universal Service Fund (USF) contributions (the FCC sets the federal rate quarterly), state and local 911 fees, and any other government-chargeable fees, shown as separate line items. Second, our own cost-recovery fees, the Regulatory Recovery Fee and the Emergency E911 Services Fee, which are our charges and not government taxes; these are described, with amounts, in Schedule 1, and more detail is at <a href="https://www.dialstack.ai/regulatory-fees" target="_blank" rel="noopener noreferrer">www.dialstack.ai/regulatory-fees</a>.</p>
<p><span class="lead-in">Late payments and disputes.</span> We may suspend the service for overdue amounts until they're paid. Overdue amounts accrue a late charge of the greater of 1.5% per month or the maximum the law allows, and you'll reimburse reasonable collection costs and attorneys' fees. Although your Platform Partner is the primary collector, we keep the right to collect directly and enforce your payment obligations. To dispute a charge, you must notify your Platform Partner (our billing agent), in writing, using the billing or support contact your Platform Partner provides, within 30 days of the invoice date, identifying the charge and the basis; a charge is treated as disputed only if submitted this way, and otherwise you waive the dispute. If your card is declined, your Platform Partner will retry up to two more times over the following two days; if it's still declined on the third try, your account may be terminated and we keep all other remedies available under this agreement and the law. If your card is declined within 30 days of opening the account, the account may be canceled immediately and its phone numbers removed.</p>
<p><span class="lead-in">Credit checks.</span> We or your Platform Partner may require credit approval before or during service and may obtain credit reports. If your financial condition doesn't reasonably justify continued service on these payment terms, we may require advance payment or terminate under Section 15.</p>

<h2>6. Service Availability</h2>
<p>We may modify, maintain, or repair the network at any time, even if that briefly interrupts the service. We will use commercially reasonable efforts to minimize disruption and to give advance notice of planned maintenance by phone, email, or similar, but failure to give any such notice is not a breach and creates no liability or credit entitlement. We provide the service on an "as is" and "as available" basis (see Section 12 for the full disclaimer). Any service credits are provided solely at our discretion, and no interruption, announced or unannounced, entitles you to a credit, refund, or other remedy except as expressly stated.</p>

<h2>7. Emergency Calls (911): Please Read This</h2>
<p>This is the most important section to understand. Our 911 service works differently from a traditional landline, and in some situations it may not work at all. <strong>You agree to make sure everyone who uses the service knows about these limits.</strong></p>
<p><span class="lead-in">911 on internet phone service has real limitations.</span> The 911/E911 component of the service does not have the same functionality or reliability as traditional wireline 911. Because it depends on power, internet, and correct location data, it can fail or be delayed in situations a landline wouldn't. You acknowledge and agree that we have advised you of the reasons to maintain at least one backup method of reaching 911 at each location, such as a cell phone or a traditional landline, and you agree to advise all of your users of the 911 limitations described in this section.</p>
<p><span class="lead-in">Situations where 911 may not work or may be delayed include:</span></p>
<ul>
  <li>A power outage, or loss of internet, at the user's location.</li>
  <li>Failure, or improper installation/configuration, of the user's broadband or VoIP hardware or software (including softphones).</li>
  <li>Suspension, disconnection, or termination of the service for any reason, including non-payment.</li>
  <li>The user's registered physical location being missing, wrong, or out of date, or the user calling 911 from a different location than the one registered.</li>
  <li>The local emergency call center not being equipped to receive or keep your number or location, which can mean they don't know who's calling or from where.</li>
  <li>Network congestion or technical factors, which can cause a busy signal or longer-than-normal wait to be answered.</li>
</ul>
<p><span class="lead-in">You must register and keep each user's location current.</span> You're required to register the physical location of each user's phone or softphone when you order the service and whenever you add a user, through our portal. The location you register is what gets sent to the emergency call taker, and it's what our system uses to route 911 calls to the right call center. If we detect that a user's network location has changed, our system may prompt them to confirm or update it, but keeping each user's location current is solely your responsibility regardless of whether any prompt is sent, and you're responsible for making sure your users respond promptly and keep their location accurate. If a location is wrong or out of date, a 911 call may go to the wrong place. When a location is updated, there may be a short delay before it's usable for 911 routing.</p>
<p><span class="lead-in">Multiple lines (MLTS).</span> If your service has two or more lines or seats, you're responsible for configuring and operating that system in line with the law, including designating administrators, managing line assignments and locations, and designating a phone number, email, or location where notice of 911 calls placed on your system should be delivered.</p>
<h3>Release and indemnity for 911.</h3>
<div class="ssa-callout ssa-callout-warn" role="note" aria-label="911 release and indemnity">
  <span class="ssa-callout-label">911 Release and Indemnity — Please Read</span>
  <p>Because of these limitations, neither we, the Platform Partner, nor our and their respective affiliates, members, officers, directors, employees, consultants, agents, licensors, suppliers, or resellers will be liable to you, your users, or any third party for any inability to dial 911 or reach an emergency operator or emergency services, and you waive all such claims and causes of action. You also release, and agree to indemnify, defend, and hold all of them harmless from, any and all claims, liabilities, damages, losses, expenses, and costs (including reasonable attorneys' fees and court costs) brought by you, your users, or any third party arising out of or related to 911/E911 service, its failure to function or function properly, our provision of it, or our failure to provide access to it. This release and indemnity is a separate allocation of risk, is not subject to the liability cap in Section 13, and survives termination.</p>
</div>

<h2>8. Phone Numbers and Special Dialing</h2>
<p><span class="lead-in">Phone numbers (DIDs).</span> When numbers are available, we'll offer you a list to choose from. You don't own the numbers assigned to you, and you can't transfer them except by porting out (below). We can change, cancel, withdraw, or move a number in our sole discretion, immediately upon notice to you. When the service ends, you may port a number out within 10 days (see Porting out); if you don't, the number reverts to us and may be reassigned, and we aren't liable for that reassignment. Don't advertise a number until it's active on your account.</p>
<p><span class="lead-in">Porting in.</span> You can port an existing number to us. While the port is in progress, you'll use a temporary number we provide. We'll support valid port-in requests and cooperate with you, but we aren't responsible for delays or rejections caused by you, your prior provider, or another third party. When you ask us to port a number in, you confirm you're authorized to transfer it and that your request is accurate and complete.</p>
<p><span class="lead-in">Porting out.</span> You (or a provider acting for you) can request to port a number away from us. We'll support and promptly cooperate with valid port-out requests. Until the port-out is complete and you terminate service for that number, you stay bound by this agreement for it and keep paying the monthly fees. Porting out and terminating this agreement doesn't end any separate agreement you have with your Platform Partner. If this agreement or the service ends and you don't port a number out within 10 days, that number becomes ours and you have no further claim to it.</p>
<p><span class="lead-in">711 (relay services).</span> You can dial 711 to reach Telecommunications Relay Services. If a user's registered location isn't their actual location, 711 calls may not route to the correct relay center.</p>
<p><span class="lead-in">What's not included.</span> The service doesn't include operator or directory assistance and doesn't support 900 or 976 calls. It may not support 311, 411, 511, or other X11 dialing (other than 911 and 711) in all areas.</p>

<h2>9. Privacy and Your Data</h2>
<p><span class="lead-in">Our Privacy Policy governs.</span> Our handling of your data and personal information is governed by our Privacy Policy at <a href="https://www.dialstack.ai/privacy" target="_blank" rel="noopener noreferrer">www.dialstack.ai/privacy</a>, which you confirm you've reviewed and agree to.</p>
<p><span class="lead-in">Sharing needed to run the service.</span> To provide, support, bill, and maintain the service, we may share your data with (a) your Platform Partner, including call metadata, usage data, call recordings and transcripts, and related analytics made available through our platform for use in the Platform Partner's products, and (b) our infrastructure providers, as needed to deliver the service.</p>
<p><span class="lead-in">CPNI (your calling records).</span> As a carrier, we collect Customer Proprietary Network Information, the kinds of service you buy, how you use it (like your calling records), and related billing information. (Your name, number, and address aren't CPNI.) We don't sell or share your CPNI with anyone outside of us and those authorized to represent us or perform functions on our behalf related to the service (including your Platform Partner who provides the service to you), except as the law requires or you authorize. You authorize us to share CPNI with your Platform Partner to provision, support, bill, and maintain the service and the Platform Partner's integrated products, including making call metadata, usage data, and analytics available through our platform. Federal law lets us and our agents use CPNI to provide, bill, and collect for your service, and we may use or disclose it for legal reasons such as responding to a court order, investigating fraud, or protecting our rights, our network, or other users. <strong>Neither we nor your Platform Partner will use or disclose CPNI for marketing.</strong> This doesn't cover information you give your Platform Partner directly under a separate agreement.</p>
<p><span class="lead-in">De-identified and aggregated data.</span> We may collect, use, and keep de-identified, aggregated data from your use of the service (like call metadata, usage patterns, and performance metrics) to improve, develop, and train our products, services, and technology, including machine-learning models. This data won't identify you or any user, and we won't try to re-identify it. It does <strong>not</strong> include the contents of your communications (call audio, voicemail content, message text) unless you've separately opted into a program that expressly allows it. This limit applies only to using your communications content to develop or train our models. It does not limit our processing of your content to provide the service and the features you use, such as voicemail, call recording, transcription, and AI call summaries, which is covered by the license in Section 4.</p>

<h2>10. Our Intellectual Property and Software</h2>
<p><span class="lead-in">We own the service.</span> We and our licensors own all rights in the service, our software, our content, and the platform and interfaces used to access it, including anything we develop while providing the service (even if it grew out of your input), which you assign to us to the extent it would otherwise be yours. You don't get any ownership rights by using the service. Don't copy, modify, sell, distribute, or create derivative works from the service or our content, and don't remove proprietary notices or use our names, logos, or branding without permission.</p>
<p><span class="lead-in">Your license to use our software.</span> We grant you a limited, non-exclusive, revocable, non-transferable, non-sublicensable license to use the software we provide as part of the service, within the United States, for your provisioned users and services, for as long as your subscription lasts.</p>
<p><span class="lead-in">Updates.</span> If we provide downloadable or installable software as part of the service, it may automatically download and install updates (bug fixes, improvements, new features), and as a condition of using that software you agree to allow these updates to install.</p>

<h2>11. Confidentiality</h2>
<p>Our business and technical information, pricing, discounts, and other business data, whether marked confidential or identified as confidential (verbal information qualifies if designated confidential at the time and summarized to you in writing within 30 days), is our "Confidential Information." You agree to keep it strictly confidential, protect it with at least reasonable care, and not use or disclose it except as allowed here or to perform your obligations. This doesn't cover information that is public through no fault of yours, that you lawfully received from a third party free to share it, that you can show you already knew, or that you independently developed. If you're legally compelled to disclose it, you may, but only to the extent required and, where allowed, after promptly notifying us so we can seek a protective order (and you'll reasonably help us do so). <strong>Your confidentiality obligations survive indefinitely after this agreement ends.</strong> When the agreement ends, you'll stop using our Confidential Information and promptly return or destroy it (and certify that on request).</p>

<h2>12. Warranties and Disclaimers</h2>
<p><span class="lead-in">Mutual basics.</span> Each of us represents that we're properly organized and in good standing, have the authority to enter into and perform this agreement, won't violate any law or other agreement by doing so, and that this agreement is binding and enforceable.</p>
<p><span class="lead-in">Everything else is "as is."</span> Except for the basic representations just above:</p>
<div class="ssa-callout" role="note" aria-label="Disclaimer of warranties">
  <span class="ssa-callout-label">Disclaimer of Warranties</span>
  <p>The service, software, websites, and your account are provided "as is" and "as available," and you use them at your own risk. To the maximum extent allowed by law, we and our licensors and suppliers (including your Platform Partner) disclaim all other warranties, express, implied, or statutory, including the implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the service will be uninterrupted, error-free, secure, timely, virus-free, or accurate, that defects will be fixed, that it will meet your requirements or hit any particular uptime or call quality, or that it will prevent toll fraud or that other carriers won't block your traffic.</p>
</div>
<p>We're not responsible for damage to your devices or loss of data from using the service, and we have no obligation to retain your information, content, or communications beyond what the law requires for call detail records. Any equipment warranty is only what's stated in Schedule 1.</p>

<h2>13. Limitation of Liability</h2>
<div class="ssa-callout" role="note" aria-label="Limitation of liability">
  <span class="ssa-callout-label">Limitation of Liability</span>
  <p>Neither we nor our licensors or suppliers (including your Platform Partner) will be liable for any incidental, special, statutory, indirect, or consequential damages, lost profits or revenue, lost or corrupted data, toll fraud, or cost of cover or substitute services, arising out of or related to this agreement or the service. Our total liability under this agreement will not exceed the fees you actually paid for the service in the two (2) months before the event that gave rise to the liability. These limits apply no matter the theory of liability (contract, tort, negligence, or otherwise) and even if a limited remedy fails of its essential purpose. Nothing in this agreement excludes or limits our liability for our own gross negligence, willful misconduct, or fraud, or for any liability that cannot be excluded or limited under applicable law.</p>
</div>
<p>(The 911 release and indemnity in Section 7 is a separate allocation of risk and is not subject to this cap.)</p>

<h2>14. Your Indemnification of Us</h2>
<p>You agree to indemnify, defend, and hold us harmless, along with our affiliates, officers, directors, employees, consultants, agents, licensors, suppliers, providers, resellers, and your Platform Partner, from any third-party claims, and the resulting liabilities, damages, losses, costs, and reasonable attorneys' fees, that arise out of or relate to:</p>
<ul>
  <li>your use of the service in any way other than strictly as allowed by this agreement;</li>
  <li>your breach of this agreement, including your representations and warranties;</li>
  <li>your violation of any law or regulation, including fraudulent or illegal use of the service by you or your users (for example, illegal robocalls, caller-ID spoofing, telemarketing or messaging that violates the TCPA, or unlawful call recording);</li>
  <li>your negligence or willful misconduct; or</li>
  <li>any claim that Your Content or your users' content infringes or misappropriates someone's intellectual property or other rights.</li>
</ul>
<p>This indemnity applies to the fullest extent permitted by law and regardless of the indemnified parties' concurrent negligence, but it does not cover a claim to the extent it is caused by our own gross negligence, willful misconduct, or fraud. It is in addition to the separate 911 indemnity in Section 7.</p>
<p><span class="lead-in">How this works.</span> We'll notify you reasonably promptly of any claim we want covered (a delay only reduces your obligation to the extent it actually prejudices you). You control the defense and settlement using qualified counsel, except that you can't settle in a way that imposes any obligation or liability on us, admits our fault, or doesn't fully release us, without our prior written consent. We may join with our own counsel at our own expense, and you'll reasonably cooperate.</p>
<p class="ssa-note">Plain-language note, illustrative only and not limiting the scope above: this indemnity runs one way, from you to us. That is deliberate and standard for a regulated carrier. Because we carry your traffic on our licensed network, conduct on your account can expose us to regulators and third parties even though the conduct is yours.</p>

<h2>15. Term and Termination</h2>
<p><span class="lead-in">Term.</span> The agreement starts on your effective date and continues until you cancel it or it is terminated as described below. There is no fixed term.</p>
<p><span class="lead-in">Reducing or canceling your service.</span> There is no minimum commitment and no early-termination fee. You can reduce or remove resources, or cancel entirely, at any time; billing runs month-to-month. Whenever you reduce or remove resources, including reducing them to zero, the billing rules in Section 5 and Schedule 1 apply: the change takes effect at the start of the next billing period, recurring fees already billed in advance for the current month are not refunded, and usage is billed in arrears. Reducing your resources to zero has the same effect as canceling.</p>
<p><span class="lead-in">Termination for breach.</span> Either of us may terminate if the other materially breaches and doesn't cure within 30 days of written notice (if the breach can be cured). We may suspend or terminate immediately on written notice if you (i) don't pay undisputed amounts within 15 days after notice that payment is past due, or (ii) violate the scope-of-use or prohibited-use rules in Section 3.</p>
<p><span class="lead-in">What happens when it ends.</span> When the agreement ends for any reason: you'll stop using the service and software and destroy any copies of end-user software you can; all licenses and subscriptions end; we may deactivate or delete your account and its contents and cut off access; you'll lose access to your assigned numbers unless you ported them out first; you'll return any equipment not paid for in full; and you'll promptly pay everything you owe.</p>
<p><span class="lead-in">What survives.</span> Any provision that by its nature should continue after termination does, and this is in addition to (not limited by) the following, which expressly survive: the enforcement and no-liability provisions of Section 3; Section 4 (your content and the license to us); Section 5 (amounts owed, billing, and collection); Section 9 (privacy, CPNI, and de-identified data); the 911 release and indemnity in Section 7; Section 10 (intellectual property); Section 11 (confidentiality); Section 12 (disclaimers); Section 13 (limitation of liability); Section 14 (your indemnification of us); this Section 15; all of Section 16 (including governing law, dispute resolution, and the time limit on claims); and the number-surrender terms in Section 8. Listing these does not mean any unlisted provision fails to survive where its nature requires it.</p>

<h2>16. General Terms</h2>
<p><span class="lead-in">Governing law and venue.</span> This agreement, and any dispute arising out of it, is governed by California law (without its conflict-of-laws rules and excluding the UN Convention on Contracts for the International Sale of Goods). Disputes will be heard in the state or federal courts for the County of San Diego, California, and both of us waive objections to that venue and jurisdiction.</p>
<p><span class="lead-in">Injunctive relief.</span> If you breach or threaten to breach this agreement, we can seek injunctive relief (without posting a bond) from any court with jurisdiction, on top of our other remedies.</p>
<p><span class="lead-in">Time limit on claims.</span> Any claim must be brought within one year after the cause of action arises, or one year after the party bringing it actually knew of the claim, whichever is later, regardless of any longer statute of limitations.</p>
<p><span class="lead-in">Changes to these terms.</span> We may update these terms by posting a revised version and giving you at least 30 days' notice of material changes. Notice may be by email to the address on your account or through your Platform Partner's product or portal, where you actually use the service. If a change is required sooner by law or a regulator, we'll give as much notice as practical. Continuing to use the service after the effective date means you accept the new terms; if you don't agree, you can terminate by giving written notice before the change takes effect.</p>
<p><span class="lead-in">Entire agreement.</span> This agreement, with its Schedules and your service orders, is the entire understanding between us on this subject and supersedes any earlier or contemporaneous communications.</p>
<p><span class="lead-in">Assignment and subcontractors.</span> You can't assign this agreement or your rights or obligations without our prior written approval, and any attempt to do so is void. We may partner with others (including your Platform Partner) and subcontract any of our obligations.</p>
<p><span class="lead-in">Force majeure.</span> We're not liable for delays or failures caused by events beyond our control, such as fire, flood, acts of God, war, strikes, government action, civil disturbance, epidemic or pandemic, or inability to get materials, underlying services, or transportation.</p>
<p><span class="lead-in">Notices.</span> We may give you any notice under this agreement by email to the address on your account, or through the service or your Platform Partner's product or portal; that notice is effective when sent. You may give us notice by email to <a href="mailto:legal@dialstack.ai">legal@dialstack.ai</a>, effective when we receive it. Keep the email address on your account current, a notice we send to the address on file is effective even if you failed to update it.</p>
<p><span class="lead-in">Other standard terms.</span> If any provision is found unenforceable, the rest stays in effect and the provision is narrowed to the minimum needed to be enforceable. A waiver only counts if it's in writing, and not enforcing a right once doesn't waive it. This agreement creates no third-party beneficiaries, except that your Platform Partner may enforce its right to collect fees on our behalf and the releases, disclaimers, limitations, and indemnities in Sections 7, 12, and 13 that run in its favor. Electronic acceptance is as valid as a handwritten signature. Headings are for convenience only. We and you are independent contractors, neither is the other's agent, and you handle your own taxes, benefits, and employment matters for your personnel. Both of us will follow applicable laws and regulations, including export laws, when using the service.</p>

<h2>Schedule 1: Services and Fair Use</h2>
<p class="ssa-note">Your subscription rates, the per-User license fee, the per-phone-number (DID) fee, and the per-location VoiceAI fee, are shown in your account portal, because those are the charges that scale as you add services. The other charges in this Schedule are stated here.</p>
<h3>1. What the service includes</h3>
<p>We provide hosted VoIP communications: voice calling, direct inward dialing (DID) phone numbers, voicemail, call-management features, and related functionality, delivered through our platform. You can access the service through your Platform Partner's product, a web portal and desktop or mobile apps, or the phones and devices you use with the service.</p>
<h3>2. Service components</h3>
<p>Your account may include user licenses, local and toll-free phone numbers, and VoiceAI locations, among other components. The components on your account and their per-User, per-number, and per-location rates are shown in your portal. Recurring fees are billed monthly in advance based on the resources provisioned as of each billing date (see Section 5).</p>
<h3>3. Regulatory recovery fees</h3>
<p>We charge the following fees to recover costs we incur as a carrier. <strong>These are our charges, not government taxes, and they are not mandated by any government.</strong> Genuine government taxes, fees, and surcharges (such as USF and state and local taxes) are separate and are passed through as described in Section 5 of the agreement.</p>
<ul>
  <li><strong>Regulatory Recovery Fee: $1.45 per User per month.</strong> Offsets our regulatory compliance costs (state PUC filings, USF administration, TCPA and other compliance systems, and related overhead).</li>
  <li><strong>Emergency E911 Services Fee: $0.50 per phone number per month.</strong> Offsets our cost of delivering E911 (PSAP connectivity, location-database provisioning, and upstream E911 provider costs).</li>
</ul>
<p>These fees may change as our costs change; we'll use commercially reasonable efforts to give at least 10 business days' notice of a change to the email on file.</p>
<h3>4. Fair Use Policy</h3>
<p>The service includes unlimited domestic calling (excluding international, toll-free, and per-minute-rated calls), subject to a fair use limit. Your account receives a pooled allowance of 2,000 minutes per User per month, calculated as 2,000 times the average daily User count for the billing period. Total domestic minutes used by the account are measured against this pool, and minutes over the pooled allowance are billed at $0.015 per minute, rounded up.</p>
<p><span class="lead-in">Overage billing.</span> Fair use overage appears as a one-time charge on the following month's bill.</p>
<p><span class="lead-in">Exclusions.</span> Calls to toll-free numbers aren't included in the fair use allowance and are billed separately per minute. International calling is currently blocked; if we offer it in the future, it will be billed per minute and will not count toward the fair use allowance.</p>
<p><span class="lead-in">VoiceAI.</span> VoiceAI locations include inbound VoiceAI minutes under a separate fair use policy from the unlimited domestic calling above, and are measured separately, not in the User fair use pool. Each VoiceAI location receives 500 minutes per month, prorated for the part of the month it was provisioned, pooled across all VoiceAI locations on the account. Minutes over the pooled VoiceAI allowance are billed at $0.05 per minute, rounded up. VoiceAI overage appears as a one-time charge on the following month's bill.</p>
<h3>5. Usage-based and one-time charges</h3>
<p>Usage-based charges are billed monthly in arrears based on actual usage. They include fair-use overage (rates and billing timing are in Section 4) and per-minute charges for inbound calls to your toll-free numbers, billed at the rate stated in your service order. One-time charges include a one-time account activation fee of $10.00 per account. Any other one-time charges are stated in your service order.</p>
<h3>6. Billing mechanics</h3>
<p>Recurring fees are billed monthly in advance; usage, overage, and one-time charges are billed monthly in arrears for the prior month. On each billing date, recurring fees are calculated on the resources provisioned (Users, phone numbers, VoiceAI locations) as of that date and cover the month then beginning. Resources added mid-month are charged a prorated recurring fee for the rest of the month, on the following invoice. Resources removed mid-month stop incurring recurring fees from the next billing date; recurring fees already billed in advance for the current month are not refunded or credited.</p>
<h3>7. Equipment</h3>
<p>Any equipment you buy in connection with the service is obtained through your Platform Partner and governed by your terms with them.</p>
`;
